repos:
  - repo: https://github.com/adrienverge/yamllint
    rev: 79a6b2b1392eaf49cdd32ac4f14be1a809bbd8f7 # v1.37.1
    hooks:
      - id: yamllint
        args: [-s]

  - repo: https://github.com/hadolint/hadolint
    rev: b3555ba9c2bfd9401e79f2f0da68dd1ae38e10c7 # v2.12.0
    hooks:
      - id: hadolint-docker
        entry: hadolint
        files: (^|/)(Containerfile|Dockerfile)$
